### ISSUE TITLE
update-props.js:27 Uncaught TypeError: Cannot use 'in' operator to search for '0' in white-space: pre-wrap;

### ISSUE THREAD

**Issue by joefitzgerald** [atom/etch#45]
<img width="628" alt="screen shot 2017-03-05 at 10 40 10 pm" src="https://cloud.githubusercontent.com/assets/744740/23598046/ee643c3c-01f4-11e7-824b-9c0c3de1207b.png">

Affected in `0.9.0` > `0.9.2`. Was not an issue in `0.8.0`, and reverting fixes the issue.

**Comment by thomasjo** [comment]
I think a minimal repro example would be beneficial (if not necessary). Also, from your description I'm not entirely sure if this is a problem in the entire 0.9.x range, or just 0.9.2. I suspect what you meant the former.

There's been [54 commits](https://github.com/atom/etch/compare/v0.8.0...master) since 0.8.0, so it's extremely like that there have been breaking changes caused by e.g. switching away from the [`virtual-dom` library](https://github.com/atom/etch/pull/41), or related changes.

**Comment by nathansobo** [comment]
@joefitzgerald Are you passing `style` as a string?

**Comment by nathansobo** [comment]
0.9.4 should address this issue.

**Comment by joefitzgerald** [comment]
Yep, style is being passed as a string.
