### ISSUE TITLE
onChange not working

### ISSUE THREAD

**Issue by nousacademy** [atom/etch#76]
`<form onSubmit={this.handleSubmit} className="input-fields">
                  <b>Name</b>: <input type="text" value={ this.state.configKey } className="input-text native-key-bindings" onChange={ this.state.configKey }/>
                  <b>Value</b>: <input type="text" value={ this.state.configVal } className="input-text native-key-bindings" onChange={ this.state.configVal }/><br/>
                  <input type="submit" value="Save Project Moov Config" className="btn mv-consoleBtn" />
                </form>`

I'm trying to grab these input values for a form im submitting, but I'm not getting the values. The onChange doesnt even register a console.log, it only fires on page load

**Comment by BinaryMuse** [comment]
Unlike React, `onChange` fires attaches a `change` event listener on the DOM node. [From MDN](https://developer.mozilla.org/en-US/docs/Web/Events/change):

> Depending on the kind of form element being changed and the way the user interacts with the element, the `change` event fires at a different moment:
> ...
> When the element loses focus after its value was changed, but not commited (e.g. after editing the value of `<textarea>` or `<input type="text">`).

In the example code above, you have `onChange` set to state values, instead of change handlers. I've fixed that and you can see an example at https://jsbin.com/suhojey/edit?html,js,output. In that example, you can see that you can type in the field and then click on some other part of the page to make the `console.log` appear.

If you want to see the log on every key press, you'll need to use the [`input` event](https://developer.mozilla.org/en-US/docs/Web/Events/input). You can see an example of this at https://jsbin.com/hevesog/1/edit?html,js,output, and this shows a `console.log` on every key press.

---

This doesn't appear to be a problem with Etch, so I'm going to close this issue. Let us know if you have any other problems.
