### ISSUE TITLE
TypeScript in etch

### ISSUE THREAD

**Issue by oleggromov** [atom/etch#80]
Hello, `etch` team,

To start off, I really appreciate Atom as a project and initiative driven by passionate contributors. Recently, I decided to dive deeper into how it works and discovered `etch`. I love component-based UI building approach and really like the idea of having a small library powering the entire complex UI.

This discovery is driven by an article I'm working on, which promotes TypeScript usage and is intended to give concrete recipes for TS integration into real-world projects. I think you're already guessing what I'm getting at. Alongside the article development, I'm curious and want to contribute to the project. As I said, I love the component approach and want to work toward improving my understanding of it from different sides, not only from a user perspective.

Which brings me straight to the point: how would you feel about transforming `etch` codebase into TypeScript? I would love to do it solving all the issues popping up along the road, but for that, for sure, I need your consent. In case you haven't envisioned such a future for the library please share your ideas on how to keep codebase complexity and developer confidentiality in check. It would be incredibly valuable to me! 

And last but not least, I'm proceeding from the presumption that we're on the same page about advantages TypeScript brings to a project like `etch`. Since it's a foundation module for Atom, a tool that's used by millions I assume, it's better to be extremely reliable. In my opinion, a module like that would benefit most from static-typed implementation - although, the might be zero known bugs at the moment.

Thanks for your time and looking forward to getting your answer! 
Kind regards, 
Oleg.

**Comment by lee-dohm** [comment]
Thank you very much for the well-thought-out and -presented ideas. We understand and agree that TypeScript can bring many benefits to the table. On the other hand, we aren't really intending on growing etch beyond where it is at this point in time, it is definitely in maintenance mode. Because of this, we don't want to take on the risk that a conversion to TypeScript would entail.

On the other hand, please feel free to fork etch and create your own TypeScript version of it. It would be very interesting to see where you go with it!

Thanks again for reaching out and your interest in etch :grinning:
